name: easy_budget
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.9
  git_hooks: 1.0.1
  dart_pre_commit: ^5.2.1
  sqflite: ^2.3.0
  path: ^1.8.3
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  fonts:
  - family: Inter
    fonts:
    - asset: fonts/Inter-Regular.ttf
    - asset: fonts/Inter-Black.ttf
    - asset: fonts/Inter-Bold.ttf
    - asset: fonts/Inter-ExtraBold.ttf
    - asset: fonts/Inter-ExtraLight.ttf
    - asset: fonts/Inter-Light.ttf
    - asset: fonts/Inter-Medium.ttf
    - asset: fonts/Inter-SemiBold.ttf
    - asset: fonts/Inter-Thin.ttf


dart_pre_commit:
  outdated: false
  pull-up-dependencies: false